# Generated by Django 2.0.6 on 2020-03-19 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_article_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(default='杂谈', max_length=16),
        ),
    ]
