# Generated by Django 2.0.6 on 2020-03-20 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(default='美文', max_length=16),
        ),
    ]
